### ISSUE TITLE
Update README.md Infos

### ISSUE THREAD

**Issue by localleon** [localleon/barco-slm-network#10]
The README.md should be updated to include the following infos:
- Project now supports Go11 Modules
- Dependencies Section should habe a link to`go.mod` and `go.sum`

**Comment by gustavogalisa** [comment]
Hey! I can do that! Do you want me to include it in a new section called "New features" or something?

**Comment by localleon** [comment]
Hello, i would love a PR from you. I personally would include it in the #Dependencies Sections . The Go Modules support isn't a dramatic change. It will be mentioned in the v2.1 Milestone
